// Generate hub 3proxy.cfg — multi-port, multi-user, bind per slot IP (per shard)
import { randomBytes } from 'crypto';
import { prisma } from '../../db/prisma';
import { getMikrotikService } from '../mikrotik/MikrotikService';
import {
  hubAdminPort,
  hubExtHttpPort,
  hubExtSocksPort,
  hubHttpPort,
  hubLogFilePattern,
  hubMaxConn,
  hubMountList,
  hubShardContainerIp,
  hubShardId,
  hubShardSubnet,
  hubSocksPort,
  hubSlotIp,
  hubCfgFile,
  hubSlotIpsFile,
  HUB_LOG_DIR_CONTAINER,
  HUB_MONITOR_USERNAME,
  HUB_SHARD_COUNT,
} from '../../lib/hubUtils';
import {
  buildUserLimitLines,
  buildUserTimeAllowLine,
  buildUserTimeDenyLine,
  isLimitExpired,
  type ProxyLimitInput,
} from '../../lib/hubLimitUtils';
import { logger } from '../../lib/logger';
import { config } from '../../lib/config';

const HUB_MONITOR_PASSWORD_KEY = 'hub.monitorPassword';

/** Structured log line — %D = duration ms (verified in 3proxy log.c). */
export const HUB_LOGFORMAT =
  '- +_L%t.%. %E %U %C %c %n %r %O %I %N %D';

function escapeCfgValue(v: string): string {
  return v.replace(/\\/g, '\\\\').replace(/"/g, '\\"');
}

async function readMonitorPasswordFromHubCfg(): Promise<string | null> {
  try {
    const mik = getMikrotikService();
    const raw = await mik.sshExec('/file/print detail where name=disk1/hub-3proxy.cfg', 15_000);
    const m = raw.match(new RegExp(`${HUB_MONITOR_USERNAME}:CL:([A-Za-z0-9_-]+)`));
    return m?.[1] ?? null;
  } catch {
    return null;
  }
}

export async function getHubMonitorPassword(): Promise<string> {
  const cfgPass = await readMonitorPasswordFromHubCfg();
  const row = await prisma.setting.findUnique({ where: { key: HUB_MONITOR_PASSWORD_KEY } });

  if (cfgPass && row?.value !== cfgPass) {
    await prisma.setting.upsert({
      where: { key: HUB_MONITOR_PASSWORD_KEY },
      create: { key: HUB_MONITOR_PASSWORD_KEY, value: cfgPass },
      update: { value: cfgPass },
    });
    logger.info('hub monitor password synced from hub-3proxy.cfg');
    return cfgPass;
  }
  if (row?.value) return row.value;
  if (cfgPass) {
    await prisma.setting.upsert({
      where: { key: HUB_MONITOR_PASSWORD_KEY },
      create: { key: HUB_MONITOR_PASSWORD_KEY, value: cfgPass },
      update: { value: cfgPass },
    });
    return cfgPass;
  }

  const pass = randomBytes(18).toString('base64url');
  await prisma.setting.upsert({
    where: { key: HUB_MONITOR_PASSWORD_KEY },
    create: { key: HUB_MONITOR_PASSWORD_KEY, value: pass },
    update: { value: pass },
  });
  return pass;
}

type HubProxyRow = {
  pppoeIdx: number;
  username: string;
  password: string;
  enabled: boolean;
  proxyType: string;
  limit?: ProxyLimitInput | null;
};

function buildCfg(
  proxies: HubProxyRow[],
  shardId: number,
  monitorPassword: string,
): string {
  const containerIp = hubShardContainerIp(shardId);
  const enabled = proxies.filter(p => p.enabled && !isLimitExpired(p.limit));
  const adminPort = hubAdminPort(shardId);
  const shardNet = hubShardSubnet(shardId);
  const mon = escapeCfgValue(HUB_MONITOR_USERNAME);
  const monPass = escapeCfgValue(monitorPassword);

  const lines: string[] = [
    `# hub-3proxy.cfg shard${shardId + 1} — auto-generated by webuiproxymikrotik`,
    'config /etc/3proxy/3proxy.cfg',
    'nserver 1.0.0.1',
    `nscache ${config.hub.nscache}`,
    'timeouts 1 5 30 60 180 1800 15 60',
    `maxconn ${hubMaxConn(enabled.length)}`,
    'auth strong',
  ];

  if (config.logs.hubRequestLog) {
    const logFile = hubLogFilePattern(shardId);
    lines.push(`log ${logFile} D`, 'rotate 30', `logformat "${HUB_LOGFORMAT}"`);
  }

  const userParts: string[] = [`${mon}:CL:${monPass}`];
  if (enabled.length) {
    userParts.push(
      ...enabled.map(p => `${escapeCfgValue(p.username)}:CL:${escapeCfgValue(p.password)}`),
    );
  }
  lines.push(`users ${userParts.join(' ')}`);

  // Admin HTTP interface — metrics via GET /S (XML). -s = read-only scope.
  lines.push('flush');
  lines.push(`allow ${mon} 172.17.0.0/16,${shardNet},127.0.0.1 * * * ADMIN`);
  lines.push('deny * * * * ADMIN');
  lines.push(`admin -s -p${adminPort} -i${containerIp}`);

  // Traffic counters — countall quota (per-user numbers assigned in hubLimitUtils)
  const counterFile = `${HUB_LOG_DIR_CONTAINER}/counters-shard${shardId + 1}.bin`;
  lines.push(`counter ${counterFile} D ${HUB_LOG_DIR_CONTAINER}/counter-reports-shard${shardId + 1}`);
  for (const p of enabled) {
    for (const limLine of buildUserLimitLines(p.username, p.pppoeIdx, p.limit)) {
      lines.push(limLine);
    }
  }

  lines.push('flush');
  for (const p of enabled) {
    const ip = hubSlotIp(p.pppoeIdx);
    const http = hubHttpPort(p.pppoeIdx);
    const socks = hubSocksPort(p.pppoeIdx);
    const extHttp = hubExtHttpPort(p.pppoeIdx);
    const extSocks = hubExtSocksPort(p.pppoeIdx);
    const u = escapeCfgValue(p.username);
    const timeAllow = buildUserTimeAllowLine(p.username, p.limit);
    if (timeAllow) lines.push(timeAllow.replace(p.username, u));
    if (ip !== containerIp) {
      lines.push(`external ${ip}`);
    }
    if (p.proxyType === 'http' || p.proxyType === 'both') {
      if (!timeAllow) lines.push(`allow ${u}`);
      lines.push(`proxy -n -a -p${http} -i${ip}`);
      lines.push(`proxy -n -a -p${extHttp} -i${ip}`);
    }
    if (p.proxyType === 'socks5' || p.proxyType === 'both') {
      if (!timeAllow) lines.push(`allow ${u}`);
      lines.push(`socks -n -a -p${socks} -i${ip}`);
      lines.push(`socks -n -a -p${extSocks} -i${ip}`);
    }
    const timeDeny = buildUserTimeDenyLine(p.username, p.limit);
    if (timeDeny) lines.push(timeDeny.replace(p.username, u));
  }

  if (!enabled.length) {
    lines.push('allow *');
    lines.push('proxy -n -p65530 -i127.0.0.1');
  }

  return lines.join('\n') + '\n';
}

function escapeRouterOsFileContents(content: string): string {
  return content
    .replace(/\\/g, '\\\\')
    .replace(/"/g, '\\"')
    .replace(/\n/g, '\\n')
    .replace(/\r/g, '');
}

/** Ghi file RouterOS — remove + add, retry khi race "file already exists". */
async function writeRouterOsFile(
  mik: ReturnType<typeof getMikrotikService>,
  filePath: string,
  escapedContents: string,
): Promise<void> {
  for (let attempt = 0; attempt < 3; attempt++) {
    await mik.sshExec(
      `:foreach f in=[/file/find where name="${filePath}"] do={/file/remove $f}`,
      10_000,
    ).catch(() => {});
    if (attempt > 0) {
      await mik.sshExec(':delay 800ms', 5_000).catch(() => {});
    }
    const out = await mik.sshExec(`/file/add name=${filePath} contents="${escapedContents}"`, 30_000);
    if (!out.includes('failure:')) return;
    if (!out.includes('already exists')) {
      throw new Error(`${filePath} write failed: ${out.trim().slice(0, 200)}`);
    }
  }
  throw new Error(`${filePath} write failed: file already exists after retries`);
}

function buildSlotIpsFile(
  proxies: Array<{ pppoeIdx: number; enabled: boolean }>,
  shardId: number,
): string {
  const containerIp = hubShardContainerIp(shardId);
  const ips = [...new Set(
    proxies.filter(p => p.enabled).map(p => hubSlotIp(p.pppoeIdx)),
  )].filter(ip => ip !== containerIp);
  return ips.join('\n') + (ips.length ? '\n' : '');
}

export async function syncHubConfigForShard(shardId: number): Promise<void> {
  const mik = getMikrotikService();
  const all = await prisma.proxyUser.findMany({
    where: { enabled: true },
    include: { limit: true },
    orderBy: { pppoeIdx: 'asc' },
  });
  const proxies = all.filter(p => {
    try {
      return hubShardId(p.pppoeIdx) === shardId;
    } catch {
      return false;
    }
  });

  const cfgPath = hubCfgFile(shardId);
  const ipsPath = hubSlotIpsFile(shardId);
  const mountList = hubMountList(shardId);
  const monitorPassword = await getHubMonitorPassword();

  const content = buildCfg(proxies, shardId, monitorPassword);
  const escaped = escapeRouterOsFileContents(content);
  const slotIpsContent = buildSlotIpsFile(proxies, shardId);
  const escapedSlotIps = escapeRouterOsFileContents(slotIpsContent);

  await writeRouterOsFile(mik, cfgPath, escaped);
  if (slotIpsContent.trim()) {
    await writeRouterOsFile(mik, ipsPath, escapedSlotIps);
  } else {
    await mik.sshExec(`:foreach f in=[/file/find where name="${ipsPath}"] do={/file/remove $f}`, 10_000).catch(() => {});
  }

  await mik.sshExec(`:do {/container/mounts/remove [find list=${mountList}]} on-error={}`, 10_000);
  await mik.sshExec(
    `/container/mounts/add list=${mountList} src=${cfgPath} dst=/etc/3proxy/3proxy.cfg`,
    10_000,
  );
  if (slotIpsContent.trim()) {
    await mik.sshExec(
      `/container/mounts/add list=${mountList} src=${ipsPath} dst=/etc/3proxy/hub-slot-ips`,
      10_000,
    );
  }

  logger.info({ shardId, slots: proxies.length, adminPort: hubAdminPort(shardId) }, 'syncHubConfigForShard OK');
}

export async function listActiveHubShardIds(): Promise<number[]> {
  const proxies = await prisma.proxyUser.findMany({
    where: { enabled: true },
    select: { pppoeIdx: true },
  });
  const ids = new Set<number>();
  for (const p of proxies) {
    try {
      ids.add(hubShardId(p.pppoeIdx));
    } catch { /* skip out-of-range */ }
  }
  return [...ids].sort((a, b) => a - b);
}

/** Shards có proxy enabled VÀ hub container đang chạy — tránh /container/shell lỗi "no such item". */
export async function listTailableHubShardIds(): Promise<number[]> {
  const { getMikrotikService } = await import('../mikrotik/MikrotikService');
  const { hubShardIdFromContainerName } = await import('../../lib/hubUtils');
  const active = new Set(await listActiveHubShardIds());
  if (!active.size) return [];

  const running = new Set<number>();
  const containers = await getMikrotikService().getContainers({ fresh: true }).catch(() => []);
  for (const c of containers) {
    const up = c.healthy === true
      || String((c as { running?: string | boolean }).running) === 'true'
      || ['running', 'healthy'].includes(String(c.status || '').toLowerCase());
    if (!up) continue;
    const sid = hubShardIdFromContainerName(c.name);
    if (sid != null) running.add(sid);
  }
  return [...active].filter((sid) => running.has(sid)).sort((a, b) => a - b);
}

/** Sync cfg cho mọi shard đang có proxy enabled. */
export async function syncHubConfig(): Promise<void> {
  const shards = await listActiveHubShardIds();
  if (shards.length === 0) {
    await syncHubConfigForShard(0);
    return;
  }
  for (const sid of shards) {
    await syncHubConfigForShard(sid);
  }
}

/** Pre-create mount placeholders cho tất cả shard (setup). */
export async function ensureHubShardMounts(shardId: number): Promise<void> {
  const mik = getMikrotikService();
  const cfgPath = hubCfgFile(shardId);
  const ipsPath = hubSlotIpsFile(shardId);
  const mountList = hubMountList(shardId);
  await mik.sshExec(`:do {/file/add name=${cfgPath} contents="# hub placeholder"} on-error={}`, 10_000).catch(() => {});
  await mik.sshExec(`:do {/file/add name=${ipsPath} contents=""} on-error={}`, 10_000).catch(() => {});
  await mik.sshExec(`:do {/container/mounts/remove [find list=${mountList}]} on-error={}`, 10_000);
  await mik.sshExec(`/container/mounts/add list=${mountList} src=${cfgPath} dst=/etc/3proxy/3proxy.cfg`, 10_000);
  await mik.sshExec(`/container/mounts/add list=${mountList} src=${ipsPath} dst=/etc/3proxy/hub-slot-ips`, 10_000);
}

export function maxHubShards(): number {
  return HUB_SHARD_COUNT;
}

/** @internal test helper */
export function buildHubCfgForTest(
  proxies: Parameters<typeof buildCfg>[0],
  shardId: number,
  monitorPassword: string,
): string {
  return buildCfg(proxies, shardId, monitorPassword);
}